import "./globals.css";
import { Sora } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const sora = Sora({
  subsets: ["latin"], // Vous pouvez ajouter d'autres subsets si nécessaire
  weight: ["300", "400", "700"], // Ajoutez les poids de polices nécessaires
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sora.className}>{children}</body>
    </html>
  );
}
